Durante o desenvolvimento do nosso projeto, nós aplicamos alguns filtros na nossa base de dados e salvamos os DataFrames resultantes em diferentes variáveis, sendo elas: df_1 e df_2.

Com base nisso, salve esses DataFrames em 2 arquivos csv distintos para que o time de ML possa ter acesso a esses dados de forma mais prática.

In [1]:
import pandas as pd

In [3]:
# Importação de dados
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'

dados = pd.read_csv(url, sep = ';')

In [36]:
# selecao1 = df['Quartos'] == 1
selecao1 = dados['Quartos'] ==1

dados[selecao1].to_csv('Arquivos/Dados1.csv',index=False, sep =';')

In [7]:
pd.read_csv('Dados1.csv',sep= ';')

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
2,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
3,Apartamento,Centro,1,0,0,36,1200.0,NaN,NaN
4,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0
...,...,...,...,...,...,...,...,...,...
3995,Apartamento,Barra da Tijuca,1,1,0,62,1700.0,945.0,180.0
3996,Apartamento,Leblon,1,1,1,50,4300.0,1730.0,259.0
3997,Apartamento,Copacabana,1,0,0,50,1950.0,450.0,70.0
3998,Quitinete,Copacabana,1,0,0,22,1500.0,286.0,200.0
3999,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0

In [37]:
Selecao2 = dados['Valor'] < 1200

dados[Selecao2].to_csv('Arquivos/Dados2.csv',sep = ';',index= False)

pd.read_csv('Dados2.csv', sep = ';')

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
1,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
2,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
3,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0
4,Apartamento,Olaria,3,1,0,68,1000.0,670.0,NaN
...,...,...,...,...,...,...,...,...,...
5573,Conjunto Comercial/Sala,Centro,0,0,0,32,600.0,1035.0,83.0
5574,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
5575,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
5576,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
5577,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0

## Para praticar os métodos aprendidos no decorrer dessa aula e também aprender novos, vamos realizar alguns tratamentos e seleções utilizando um arquivo csv diferente: alunos.csv.

Esse arquivo é o mesmo utilizado para resolução dos desafios da aula 1 e possui dados referentes a alunos de um curso superior.

Com base nisso, solucione os problemas propostos abaixo utilizando os conhecimentos adquiridos até aqui.

1) Verifique se a base de dados possui dados nulos e, caso tenha, realize o tratamento desses dados nulos da forma que achar mais coerente com a situação.

2) Os alunos "Alice" e "Carlos", não fazem mais parte da turma. Sendo assim, remova-os da base de dados.

3) Aplique um filtro que selecione apenas os alunos que foram aprovados.

4) Salve o DataFrame que possui apenas os alunos aprovados em um arquivo csv chamado "alunos_aprovados.csv".

Extra: Ao conferir as notas dos alunos aprovados, notamos que algumas notas estavam incorretas. As alunas que tiraram nota 7.0, na verdade, tinham um ponto extra que não foi contabilizado. Sendo assim, substitua as notas 7.0 da base de dados por 8.0. Dica: pesquise pelo método replace.

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv')

df.isnull().sum()

Nome        0
Idade       0
Notas       6
Aprovado    0
dtype: int64

In [ ]:
df = df.fillna(0)
df.isnull().sum()

Nome        0
Idade       0
Notas       0
Aprovado    0
dtype: int64

In [28]:
df[(df['Nome'] != 'Alice') | (df['Nome'] != 'Carlos') ]

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [32]:
df[(df['Aprovado'] == True)]

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
4        Beto     21   10.0      True
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
15     Mylena     29    7.0      True
17      Nadia     34    8.0      True

In [35]:
df_1 = df[(df['Aprovado'] == True)]

df_1.to_csv('Arquivos/Aprovados.csv',sep =';',index=False)